export const authConstanst = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_CATCH_ERROR: "USER_CATCH_ERROR",
  USER_REGISTER_CATCH: "USER_REGISTER_CATCH",
  USER_LOGIN_CATCH: "USER_LOGIN_CATCH",
};

export const userConstants = {
  GET_REALTIME_USERS: "GET_REALTIME_USERS",
  GET_REALTIME_MESSAGES: "GET_REALTIME_MESSAGES",
  GET_REALTIME_MESSAGES_FAILURE: "GET_REALTIME_MESSAGES_FAILURE",
  SET_USER_NAME: "SET_USER_NAME",
  SET_CHAT_START_STATUS: "SET_CHAT_START_STATUS",
  SET_OPEN: "SET_OPEN",
  DELETE_MESSAGE: "DELETE_MESSAGE",
};
